[project]
name = "python"
version = "0.1.0"
description = "Simple python client Demo (images -> backend)"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "opencv-python>=4.12.0.88",
    "orjson>=3.11.4",
    "pillow>=11.3.0",
    "websockets>=15.0.1",
]
